dwcTerms: https://raw.githubusercontent.com/tdwg/dwc/master/vocabulary/term_versions.csv
biocache:
    fields: https://biocache-ws.ala.org.au/ws/index/fields
    solr:
        host: http://localhost:8982
        collection: biocache
pipelines:
    fields: https://biocache-quoll.ala.org.au/ws/index/fields
    solr:
        host: http://localhost:8985
        collection: biocache

mappingJson: deprecated-fields.json
mappingCsv: pipeline_field_mappings.csv

# This CSV contains details of what do with fields that slip through
# deprecated-fields.json
missingFieldsMap: https://docs.google.com/spreadsheets/d/1i-sXcAZfUB-7gix8cZDIZw5JXVzBeeVwmDtJEvsxbjc/gviz/tq?tqx=out:csv&sheet=missing_fields
